# Generated by Django 3.2.5 on 2021-07-26 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 59, 50, 403962), verbose_name='fecha de publicacion'),
        ),
    ]
