# Generated by Django 3.2.5 on 2021-08-13 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 16, 15, 42, 835431), verbose_name='fecha de publicacion'),
        ),
    ]
