# Generated by Django 3.2.5 on 2021-08-13 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210813_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 16, 37, 59, 98593), verbose_name='fecha de publicacion'),
        ),
    ]
