# Generated by Django 3.2.5 on 2021-08-17 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 29, 45, 213154), verbose_name='fecha de publicacion'),
        ),
    ]
