# Generated by Django 3.2.5 on 2021-08-17 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 18, 42, 57, 57024), verbose_name='fecha de publicacion'),
        ),
    ]
