# Generated by Django 3.2.5 on 2021-08-19 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 15, 25, 2, 60954), verbose_name='fecha de publicacion'),
        ),
    ]
