# Generated by Django 3.2.5 on 2021-08-13 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 16, 37, 59, 99589), verbose_name='fecha de publicacion'),
        ),
    ]
