# Generated by Django 3.2.5 on 2021-08-17 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 48, 6, 945795), verbose_name='fecha de inscripcion'),
        ),
    ]
