# Generated by Django 3.2.5 on 2021-08-17 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_auto_20210817_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='Apellidos',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='Nombres',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 56, 29, 181980), verbose_name='fecha de inscripcion'),
        ),
    ]
