# Generated by Django 3.2.5 on 2021-08-17 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_auto_20210817_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='Apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='Nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 18, 42, 57, 57024), verbose_name='fecha de inscripcion'),
        ),
    ]
