# Generated by Django 3.2.5 on 2021-08-19 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0012_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 18, 7, 3, 885607), verbose_name='fecha de inscripcion'),
        ),
    ]
