# Generated by Django 3.2.5 on 2021-08-23 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0015_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 15, 25, 33, 592867), verbose_name='fecha de inscripcion'),
        ),
    ]
